eBookSite.Web/Areas/Admin/Controllers/OrderController.cs
using eBookSite.DataAccess.Repository;
using eBookSite.DataAccess.Repository.IRepository;
using eBookSite.Models;
using eBookSite.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using System.Diagnostics;

namespace eBookSite.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<OrderController> _logger;

        [BindProperty]

        public OrderVM OrderVM { get; set; }

        public OrderController(IUnitOfWork unitOfWork, ILogger<OrderController> logger)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;

        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> objOrderHeaderList=null;
            try
            {
                objOrderHeaderList = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();

                switch (status)
                {
                    case "inprocess":
                        objOrderHeaderList = objOrderHeaderList.Where(m => m.OrderStatus == "Processing");
                        break;
                    case "completed":
                        objOrderHeaderList = objOrderHeaderList.Where(m => m.OrderStatus == "Shipped");
                        break;
                    case "approved":
                        objOrderHeaderList = objOrderHeaderList.Where(m => m.OrderStatus == "Approved");
                        break;
                    default:
                        break;

                }
                
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return Json(new { data = objOrderHeaderList });
        }

        public IActionResult Details(int orderId)
        {
            try
            {
                OrderVM = new()
                {
                    OrderHeader = _unitOfWork.OrderHeader.GetById(m => m.Id == orderId, includeProperties: "ApplicationUser"),
                    OrderDetail = _unitOfWork.OrderDetail.GetAll(m => m.OrderHeaderId == orderId, includeProperties: "Product")
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return View(OrderVM);
        }

        [HttpPost]
        public IActionResult UpdateOrderDetail()
        {
            var orderFromDB = _unitOfWork.OrderHeader.GetById(m => m.Id == OrderVM.OrderHeader.Id);
            try
            {
                orderFromDB.Name = OrderVM.OrderHeader.Name;
                orderFromDB.State = OrderVM.OrderHeader.State;
                orderFromDB.StreetAddress = OrderVM.OrderHeader.StreetAddress;
                orderFromDB.PostalCode = OrderVM.OrderHeader.PostalCode;
                orderFromDB.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
                orderFromDB.City = OrderVM.OrderHeader.City;

                if (!string.IsNullOrEmpty(orderFromDB.Carrier))
                    orderFromDB.Carrier = OrderVM.OrderHeader.Carrier;

                if (!string.IsNullOrEmpty(orderFromDB.TrackingNumber))
                    orderFromDB.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;

                _unitOfWork.OrderHeader.Update(orderFromDB);
                _unitOfWork.Save();

                TempData["Success"] = "Order details updated successfully";
                
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return RedirectToAction("Details", new { orderId = orderFromDB.Id });
        }
        public IActionResult StartProcessing()
        {
            try
            {
                _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, "Processing");
                _unitOfWork.Save();
                TempData["Success"] = "Order details updated successfully";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return RedirectToAction("Details", new { orderId = OrderVM.OrderHeader.Id });
        }
        public IActionResult ShipOrder()
        {
            try
            {
                var orderFromDB=_unitOfWork.OrderHeader.GetById(m=>m.Id==OrderVM.OrderHeader.Id);
                orderFromDB.TrackingNumber=OrderVM.OrderHeader.TrackingNumber;
                orderFromDB.Carrier=   OrderVM.OrderHeader.Carrier;
                orderFromDB.ShippingDate = DateTime.Now;
                orderFromDB.OrderStatus="Shipped";

                _unitOfWork.OrderHeader.Update(orderFromDB);
                _unitOfWork.Save();
                TempData["Success"] = "Order shipped successfully";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return RedirectToAction("Details", new { orderId = OrderVM.OrderHeader.Id });
        }

        public IActionResult CancelOrder()
        {
            try
            {
                var orderFromDB = _unitOfWork.OrderHeader.GetById(m => m.Id == OrderVM.OrderHeader.Id);
                if(orderFromDB.PaymentStatus=="Approved")
                {
                    var options = new RefundCreateOptions
                    {
                        Reason = RefundReasons.RequestedByCustomer,
                        PaymentIntent = orderFromDB.PaymentIntentId
                    };

                    var service = new RefundService();
                    var refund = service.Create(options);
                    _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, "Cancelled", "Refunded");
                }
                else
                {
                    _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, "Cancelled", "Cancelled");
                }
                
                _unitOfWork.Save();
                TempData["Success"] = "Order cancelled successfully";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }
            return RedirectToAction("Details", new { orderId = OrderVM.OrderHeader.Id });
        }

    }
}

eBookSite.Web/Controllers/CategoryController.cs
using eBookSite.DataAccess.Data;
using eBookSite.DataAccess.Repository;
using eBookSite.DataAccess.Repository.IRepository;
using eBookSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace eBookSite.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork categoryRepo;
         public CategoryController(IUnitOfWork db)
        {
            categoryRepo = db;
        }
        public IActionResult Index()
        {
            List<Category> objCategoryList = categoryRepo.Category.GetAll().ToList();
            return View(objCategoryList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category objCategory)
        {
            if (ModelState.IsValid)
            {
                categoryRepo.Category.Add(objCategory);
                categoryRepo.Save();
                TempData["Success"] = "Category created successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            //fetch the category details from db using EF Core
            var objCategory= categoryRepo.Category.GetById(c => c.Id == id);

            if(objCategory == null)
                return NotFound();
            
            return View(objCategory);
        }

        [HttpPost]
        public IActionResult Edit(Category objCategory)
        {
            if (ModelState.IsValid)
            {
                categoryRepo.Category.Update(objCategory);
                categoryRepo.Save();
                TempData["Success"] = "Category edited successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            //fetch the category details from db using EF Core
            var objCategory = categoryRepo.Category.GetById(c => c.Id == id);

            if (objCategory == null)
                return NotFound();

            return View(objCategory);
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var category = categoryRepo.Category.GetById(m=>m.Id== id);

            if (category == null)
                    return NotFound();

            categoryRepo.Category.Remove(category);
            categoryRepo.Save();
            TempData["Success"] = "Category deleted successfully!";
            return RedirectToAction("Index");
        }

    }
}

eBookSite.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBooks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" href="~/eBookSite.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/book.png" style="width:30px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32("SessionShoppingCart") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;(@HttpContextAccessor.HttpContext.Session.GetInt32("SessionShoppingCart"))
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index">
                                    <i class="bi bi-cart"></i> &nbsp;(0)
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification" />
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2023 - Bulky Books
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eBookSite.Web/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["error"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}